- hosts:
  - 127.0.0.1
  become_method: doas
  tasks:
    - name: install hostname files
      copy: src=files/hostname.{{item}} dest=/etc/hostname.{{item}} owner=root group=wheel mode=0640
      with_items:
        - em0
        - em1
        - em2
        - trunk0
        - ppp0
    - name: create ppp peers directory
      file:
        path: /etc/ppp/peers
        state: directory
    - name: install ppp configuration
      copy: src=files/ppp/{{item}} dest=/etc/ppp/{{item}} owner=root group=wheel mode=0644
      with_items:
        - connect.three.co.uk
        - disconnect
        - peers/three.co.uk
