- hosts:
  - 127.0.0.1
  become_method: doas
  tasks:
    - name: install packages
      openbsd_pkg:
        name: ['git', 'ansible', 'tor']
        state: present
    - name: update all packages
      openbsd_pkg:
        name: "*"
        state: latest
    - name: create sd card mountpoint
      file:
        path: /sdcard
        state: directory
    - name: mount sd card
      lineinfile:
        path: /etc/fstab
        line: "sd1i /sdcard msdos rw,nodev,nosuid 1 2"
        insertafter: EOF
        state: present
    - name: install hostname files
      copy: src=files/hostname.{{item}} dest=/etc/hostname.{{item}} owner=root group=wheel mode=0640
      with_items:
        - em0
        - em1
        - em2
        - trunk0
        - ppp0
    - name: create ppp peers directory
      file:
        path: /etc/ppp/peers
        state: directory
    - name: install ppp configuration
      copy: src=files/ppp/{{item}} dest=/etc/ppp/{{item}} owner=root group=wheel mode=0644
      with_items:
        - connect.three.co.uk
        - disconnect
        - peers/three.co.uk
    - name: install sysctl.conf
      copy: src=files/sysctl.conf dest=/etc/sysctl.conf owner=root group=wheel mode=0640
    - name: install pf.conf
      copy: src=files/pf.conf dest=/etc/pf.conf owner=root group=wheel mode=0640
    - name: install resolv.conf
      copy: src=files/resolv.conf dest=/etc/resolv.conf owner=root group=wheel mode=0644
    - name: install dhcpd.conf
      copy: src=files/dhcpd.conf dest=/etc/dhcpd.conf owner=root group=wheel mode=0644
    - name: enable dhcp server
      service:
        name: dhcpd
        enabled: yes
    - name: attach nmea ld to gps dongle
      lineinfile:
        path: /etc/ttys
        line: "cuaU0   \"/sbin/ldattach nmea\"   unknown on softcar"
        insertafter: EOF
        state: present
    - name: install ntpd.conf
      copy: src=files/ntpd.conf dest=/etc/ntpd.conf owner=root group=wheel mode=0644
    - name: enable ntp server
      service:
        name: ntpd
        enabled: yes
    - name: install inetd.conf
      copy: src=files/inetd.conf dest=/etc/inetd.conf owner=root group=wheel mode=0644
    - name: enable inetd
      service:
        name: inetd
        enabled: yes
    - name: install torrc
      copy: src=files/torrc dest=/etc/tor/torrc owner=_tor group=wheel mode=0444
    - name: enable tor
      service:
        name: tor
        enabled: yes
