- hosts:
  - 127.0.0.1
  become_method: doas
  tasks:
    - name: hostname files
      copy: src=files/hostname.{{item}} dest=/etc/hostname.{{item}} owner=root group=wheel mode=0640
      with_items:
        - lo1
        - em0
        - em1
        - em2
        - trunk0
        - ppp0
